import type { ModelProvider } from '../../../domain/modelConfig';
import type { ModelRequest, ModelResponse } from '../../../domain/model';
import type { AdapterOptions, ProviderAdapter } from '../../../application/providerAdapter';

export type MockCallHandler = (
  request: ModelRequest,
  options: AdapterOptions,
) => ModelResponse | Promise<ModelResponse>;

function lastUserContent(request: ModelRequest): string {
  return [...request.messages].reverse().find((m) => m.role === 'user')?.content ?? '';
}

function defaultMockHandler(request: ModelRequest, options: AdapterOptions): ModelResponse {
  // When the caller (the Agent Runtime, SPEC-006) declares a structured-output
  // schema, return a valid task-completion result so the happy path is
  // deterministic with zero scripting. The schema failure path is reached by
  // NOT passing a responseSchema (the pre-SPEC-006 plain-text reply below).
  if (request.responseSchema) {
    const result = {
      summary: `Mock completion for: ${lastUserContent(request)}`,
      task_status: 'completed',
      artifact_proposals: [
        { title: 'Mock artifact proposal', content: 'A durable note produced by the mock provider.', type: 'note' },
      ],
      findings: [{ claim: 'Mock finding' }],
      questions_for_pi: [{ question: 'Mock question for the PI' }],
      suggested_tasks: [{ title: 'Mock suggested follow-up task', rationale: 'Auto-generated by the mock provider' }],
      memory_candidates: [{ content: 'Mock memory candidate', scope: 'project' }],
    };
    return {
      content: JSON.stringify(result),
      provider: 'mock',
      model: options.model,
      finishReason: 'stop',
      usage: { inputTokens: request.messages.length, outputTokens: 20 },
    };
  }
  return {
    content: `Mock reply to: ${lastUserContent(request)}`,
    provider: 'mock',
    model: options.model,
    finishReason: 'stop',
    usage: { inputTokens: request.messages.length, outputTokens: 8 },
  };
}

/**
 * Deterministic, scriptable adapter for tests (SPEC-005 #3). Never touches the
 * network; tests (or the demo) script responses or failures via `onCall`, so
 * acceptance tests are fully reproducible without paid live model calls.
 */
export class MockProviderAdapter implements ProviderAdapter {
  readonly provider: ModelProvider;

  private handler: MockCallHandler = defaultMockHandler;

  constructor(provider: ModelProvider = 'mock') {
    this.provider = provider;
  }

  /** Replaces the call behavior; used to script responses or throw failures. */
  onCall(handler: MockCallHandler): void {
    this.handler = handler;
  }

  async complete(request: ModelRequest, options: AdapterOptions): Promise<ModelResponse> {
    return this.handler(request, options);
  }
}
